version: 2.1
executors:
  node_exec:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: ci

jobs:
  install:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}

  lint:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn lint

  build:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn build

  deploy:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          command: |
            sudo npm install -g gh-pages
            git config user.email "ci-build@blog.net"
            git config user.name "ci-build"
      - run: yarn build
      - run:
          command: |
            git tag -a "release_${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}" -m "Release based on build ${CIRCLE_BUILD_NUM}"
            git push -q --tags
      - run: sudo gh-pages -m "Page release ${CIRCLE_BUILD_NUM} from ${CIRCLE_BRANCH}" -d packages/front/public

workflows:
  version: 2
  blog_workflows:
    jobs:
      - install:
      # - lint:
      #    requires:
      #       - install
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          requires:
            - install
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          filters:
            branches:
              only:
                - feat/9/deploy
              ignore:
                - gh-pages
          requires:
            - install
            - build
            # - test
            # - lint
            # - stylelint
