version: 2.1
executors:
  node_exec:
    docker:
      - image: circleci/node:10
        environment:
          NODE_ENV: ci

jobs:
  install:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}

  lint:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn lint

  build:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn build

  deploy:
    executor: node_exec
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn build:ci
      - add_ssh_keys:
          fingerprints:
            - "3f:5c:92:a3:bd:69:7d:59:02:3e:d5:52:7a:39:f9:8f"
      - run:
          command: |
            pwd
      - run:
          command: |
            cd packages/front/gatsby-blog
            git init
            git config user.email "ci-build@blog.net"
            git config user.name "ci-build"
            git add .
            git commit -m "Release based on build ${CIRCLE_BUILD_NUM}"
            git push -f git@github.com:bdeglane/blog.git master:gh-pages
      # - run: sudo gh-pages -m "Page release ${CIRCLE_BUILD_NUM} from ${CIRCLE_BRANCH}" -d packages/front/public

workflows:
  version: 2
  blog_workflows:
    jobs:
      - install:
      # - lint:
      #    requires:
      #       - install
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          requires:
            - install
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          filters:
            branches:
              only:
                - feat/11/fix-deploy
              ignore:
                - gh-pages
          requires:
            - install
            - build
            # - test
            # - lint
            # - stylelint
